# Generated by Django 4.2.27 on 2026-01-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cve_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('source_identifier', models.CharField(blank=True, max_length=100)),
                ('published', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('vuln_status', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='CVEConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.CharField(default='OR', max_length=10)),
                ('negate', models.BooleanField(default=False)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='cve_repository.cve')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CVSSMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('cvss_version', models.CharField(max_length=10)),
                ('vector_string', models.CharField(max_length=200)),
                ('base_score', models.FloatField()),
                ('base_severity', models.CharField(max_length=20)),
                ('exploitability_score', models.FloatField(blank=True, null=True)),
                ('impact_score', models.FloatField(blank=True, null=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvss_metrics', to='cve_repository.cve')),
            ],
        ),
        migrations.CreateModel(
            name='CVEWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('cwe_id', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='cve_repository.cve')),
            ],
        ),
        migrations.CreateModel(
            name='CVEReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='cve_repository.cve')),
            ],
        ),
        migrations.CreateModel(
            name='CVEConfigurationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.CharField(default='OR', max_length=10)),
                ('negate', models.BooleanField(default=False)),
                ('cpe_match', models.JSONField(blank=True, default=list)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cve_repository.cveconfiguration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='cve',
            index=models.Index(fields=['cve_id'], name='cve_reposit_cve_id_b93cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='cve',
            index=models.Index(fields=['published'], name='cve_reposit_publish_79e96e_idx'),
        ),
        migrations.AddIndex(
            model_name='cve',
            index=models.Index(fields=['last_modified'], name='cve_reposit_last_mo_74f8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='cve',
            index=models.Index(fields=['vuln_status'], name='cve_reposit_vuln_st_c6b639_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cvssmetric',
            unique_together={('cve', 'source', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='cveweakness',
            unique_together={('cve', 'source', 'cwe_id')},
        ),
        migrations.AlterUniqueTogether(
            name='cvereference',
            unique_together={('cve', 'url')},
        ),
    ]
