# Generated by Django 4.2.27 on 2026-01-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpe_name', models.CharField(db_index=True, max_length=500, unique=True)),
                ('cpe_name_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.TextField(blank=True)),
                ('deprecated', models.BooleanField(default=False)),
                ('deprecated_by', models.JSONField(blank=True, default=list)),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'ordering': ['cpe_name'],
            },
        ),
        migrations.CreateModel(
            name='CPEReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('href', models.URLField()),
                ('text', models.TextField(blank=True)),
                ('cpe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='cpe_repository.cpe')),
            ],
        ),
        migrations.AddIndex(
            model_name='cpe',
            index=models.Index(fields=['cpe_name'], name='cpe_reposit_cpe_nam_8464b0_idx'),
        ),
        migrations.AddIndex(
            model_name='cpe',
            index=models.Index(fields=['deprecated'], name='cpe_reposit_depreca_c8caf2_idx'),
        ),
        migrations.AddIndex(
            model_name='cpe',
            index=models.Index(fields=['last_modified'], name='cpe_reposit_last_mo_4f1aba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cpereference',
            unique_together={('cpe', 'href')},
        ),
    ]
