# Generated by Django 4.2.27 on 2026-01-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinuxCVEAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('sender', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('raw_content', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LinuxCVEAnnouncementCVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cve_id', models.CharField(db_index=True, max_length=20)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cve_references', to='linux_cve_announcements.linuxcveannouncement')),
            ],
        ),
        migrations.AddIndex(
            model_name='linuxcveannouncement',
            index=models.Index(fields=['message_id'], name='linux_cve_a_message_bc8b15_idx'),
        ),
        migrations.AddIndex(
            model_name='linuxcveannouncement',
            index=models.Index(fields=['date'], name='linux_cve_a_date_71187b_idx'),
        ),
        migrations.AddIndex(
            model_name='linuxcveannouncement',
            index=models.Index(fields=['sender'], name='linux_cve_a_sender_d21660_idx'),
        ),
        migrations.AddIndex(
            model_name='linuxcveannouncementcve',
            index=models.Index(fields=['cve_id'], name='linux_cve_a_cve_id_34957f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='linuxcveannouncementcve',
            unique_together={('announcement', 'cve_id')},
        ),
    ]
